<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>promo_banner_2</name>
   <tag></tag>
   <elementGuidId>cee4f6f2-d53a-4e36-931a-5b62c229bebb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Der Verbund für echte Gastronomen'])[1]/following::img[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>body > div.page-wrap > section > div > div.content--wrapper > div > div.listing--wrapper.visible--xl.visible--l.visible--m.visible--s.visible--xs > div.listing--container > div.supplier-promotion--banner-wrapper > a:nth-child(2) > img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://shop.gastivo.biz/media/image/93/b0/e0/Banner_Dummy1.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>promotion-banner-img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js has--history has--localstorage has--sessionstorage has--cssanimations is--chrome is--webkit&quot;]/body[@class=&quot;is--ctl-listing is--act-index&quot;]/div[@class=&quot;page-wrap&quot;]/section[@class=&quot;content-main container block-group&quot;]/div[@class=&quot;content-main--inner&quot;]/div[@class=&quot;content--wrapper&quot;]/div[@class=&quot;content listing--content&quot;]/div[@class=&quot;listing--wrapper visible--xl visible--l visible--m visible--s visible--xs&quot;]/div[@class=&quot;listing--container&quot;]/div[@class=&quot;supplier-promotion--banner-wrapper&quot;]/a[@class=&quot;icon-charakter rounded-max&quot;]/img[@class=&quot;promotion-banner-img&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Der Verbund für echte Gastronomen'])[1]/following::img[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ECHT Gastro Partner GmbH'])[1]/following::img[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zuletzt angesehen'])[1]/preceding::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gastivo'])[1]/preceding::img[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://shop.gastivo.biz/media/image/93/b0/e0/Banner_Dummy1.png')]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
   </webElementXpaths>
</WebElementEntity>
